### ISSUE TITLE
[endpoint] All Trades

### ISSUE THREAD

**Issue by choubacha** [kbacha/stellar-sdk#89]
People on the Stellar network can make offers to buy or sell assets. When an offer is fully or partially fulfilled, a trade happens.

It looks like there are a large number of params but we should be able to accept an `AssetIdentifier` as an argument the base/counter.

```rust
use stellar_client::endpoint::trade::All;
```

https://www.stellar.org/developers/horizon/reference/endpoints/trades.html

**Comment by robertDurst** [comment]
Anyone tackling this one right now?

**Comment by robertDurst** [comment]
I see that the trade resource is already created :fire:

https://github.com/kbacha/stellar-sdk/blob/master/resources/src/trade.rs

**Comment by kbacha** [comment]
Go for it!

**Comment by robertDurst** [comment]
@kbacha quick question. Since trades take counter_asset and base_asset as optional, but require the whole asset resource (code, issuer, type) does this make sense for the All struct:

```
#[derive(Debug, Default)]
pub struct All {
    base_asset: Option<AssetIdentifier>,
    counter_asset: Option<AssetIdentifier>,
    offer_id: Option<u32>,
    cursor: Option<String>,
    order: Option<Order>,
    limit: Option<u32>,
}
```

If so, how do I initialize an AssetIdentifier with this signature:

```
pub fn new(
        asset_type: &str,
        code: Option<String>,
        issuer: Option<String>,
    ) -> Result<AssetIdentifier, String> {
```

Basically, I understand what option represents, but what is best practice for using this function with options in the parameters? Would this make sense:

`AssetIdentifier::new("String", Some("String"), Some("String"))`

**Comment by kbacha** [comment]
Yup, that's how you'd initialize it.. However, I don't actually like that new function because I don't like the fact that the type is a string instead of a declaration of the actual type. I think that's it's only really used in the deserialization step:
https://github.com/kbacha/stellar-sdk/blob/master/resources/src/asset.rs#L255

I wouldn't mind if it were refactored to make it more type-safe (ie: less prone to human typos). I can see a few refactors of the resource possible:

* Move the `new` function to a different, private function just for use in `Deserialize` implementation. Or just move the code to there instead of being in a separate function. If we still want the ability to create from a string type, then we can leave it.
* Implement a function for the three types. All of these are infallible (excepting the case where possibly the code is not a correct size... which I'm unsure we need to check on our side).
```rust
pub fn native() -> AssetIdentifier;
pub fn alphanum4(code: &str, issuer: &str) -> AssetIdenifier;
pub fn alphanum12(code: &str, issuer: &str) -> AssetIdentifier;
```

As for the endpoint is concerned, adding a base or counter asset can just be a set like any other endpoint, but should take the identifier as a type.

Does this make sense?
